# Generated by Django 2.2.4 on 2019-08-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
